### ISSUE TITLE
How to Use AntD with PreactCLI

### ISSUE THREAD

**Issue by RyanSChristian** [preactjs/preact-cli#1177]
**Do you want to request a _feature_ or report a _bug_?**

Neither.

**What is the current behaviour?**

I'm rewriting an existing React application into Preact, and it uses Ant Design for a component library. Following Ant's instructions from [here](https://ant.design/docs/react/use-in-typescript), I've set up my `preact.config.js` file to try to match the example it gives for CRA

```
const babel = helpers.getLoadersByName(config, 'babel-loader')[0].rule.options;
babel.plugins.push(['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]);

const lessloader = helpers
    .getLoadersByName(config, 'proxy-loader')
    .filter((loader) => loader.loader.options.loader === 'less-loader')[0].loader.options;

lessloader.options['lessOptions'] = {
    javascriptEnabled: true,
    modifyVars: {
        '@primary-color': '#199',
    },
};
```

However, this results in the error:

```
ModuleBuildError: Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/preact-cli/lib/lib/webpack/proxy-loader.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Module.require (internal/modules/cjs/loader.js:1005:3)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.proxyLoader (/home/username/Projects/project-name/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js:22:12)
    at /home/username/Projects/project-name/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/username/Projects/project-name/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/username/Projects/project-name/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/username/Projects/project-name/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/username/Projects/project-name/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /home/username/Projects/project-name/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /home/username/Projects/project-name/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Something with the Less loader just isn't working. I can switch from using Ant's Less to instead use Ant's CSS by making this change:

```
babel.plugins.push(['import', { libraryName: 'antd', libraryDirectory: 'es', style: 'css' }]);
```

And like the docs say, this does implement proper tree-shaking, which is all well and good, but I do want to use the Less so I can override some of those default values. 

I'm testing this on pretty much the default Typescript Preact template, where my component is the following:

```
import { FunctionalComponent, h } from 'preact';
import { Button } from 'antd';

const Home: FunctionalComponent = () => {
    return (
        <div>
            <h1>Home</h1>
            <p>This is the Home component.</p>
            <Button>Hello</Button>
        </div>
    );
};

export default Home;
```

I'm not sure what else to try at this point. Seems like I'm just a hair away from making this work, but I've read in a couple places that there's been past issues with AntD and Preact, so maybe I'm wrong. 

**Please mention other relevant information.**

```
Environment Info:
  System:
    OS: Linux 5.6 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 13.13.0 - /tmp/yarn--1589421892159-0.09078026383051818/node
    Yarn: 1.22.4 - /tmp/yarn--1589421892159-0.09078026383051818/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    preact: ^10.4.1 => 10.4.1 
    preact-cli: ^3.0.0-rc.10 => 3.0.0-rc.10 
    preact-render-to-string: ^5.1.8 => 5.1.8 
    preact-router: ^3.2.1 => 3.2.1

    antd: ^4.2.2
    babel-plugin-import: ^1.13.0
    less: ^3.11.1
    less-loader: ^6.1.0
```

Thanks in advance for any help, and let me know if I've forgotten to add some detail.

**Comment by RyanSChristian** [comment]
After trying to import a Less file into my application, I noticed an error about an unknown parameter "paths" being passed to the less loader. And sure enough, after manually removing the `paths` value from the source as a quick test, everything began to work. 

The temporary solution seems to be to downgrade `less-loader` to v5, and then everything seems to work as expected. 

I'll leave this up for now, so maybe someone can see this to make the changes necessary to be compatible with `less-loader` v6
