### ISSUE TITLE
preact watch fails with emacs

### ISSUE THREAD

**Issue by mguentner** [preactjs/preact-cli#1189]
**Do you want to request a _feature_ or report a _bug_?**

**bug**

**What is the current behaviour?**

* ```$ preact watch```
* I can access 127.0.0.1:8080 and use the application :heavy_check_mark: 
* After changing a file "file.xyz" in my editor (emacs), a state file is created: ".#file.xyz"
* this file is immediately removed
* the preact process crashes:

```✖ ERROR Error: ENOENT: no such file or directory, stat '/my/code/src/components/acomp/.#index.tsx'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.0.0 start:development: `npm run -s dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@0.0.0 start:development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-05-24T17_29_55_141Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Extract from npm error log:

```
10 verbose lifecycle solidarity@0.0.0~start:development: CWD: /home/user/code/project
11 silly lifecycle solidarity@0.0.0~start:development: Args: [ '-c', 'npm run -s dev' ]
12 silly lifecycle solidarity@0.0.0~start:development: Returned: code: 1  signal: null
13 info lifecycle solidarity@0.0.0~start:development: Failed to exec start:development script
14 verbose stack Error: project@0.0.0 start:development: `npm run -s dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:315:20)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:315:20)
14 verbose stack     at maybeClose (internal/child_process.js:1051:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
15 verbose pkgid solidarity@0.0.0
16 verbose cwd /home/user/code/project
17 verbose Linux 5.6.11-arch1-1
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start:development"
19 verbose node v14.3.0
20 verbose npm  v6.14.5
21 error code ELIFECYCLE
22 error errno 1
```

Please paste the results of `preact info` here.
```
Environment Info:
  System:
    OS: Linux 5.6 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 14.3.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    preact: ^10.4.4 => 10.4.4 
    preact-cli: ^3.0.0-rc.10 => 3.0.0-rc.10 
    preact-render-to-string: ^5.1.4 => 5.1.8 
    preact-router: ^3.2.1 => 3.2.1 
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.10
```

** Note **
This happend after upgrading from 2.? to 3.0.0.

**Comment by mguentner** [comment]
I used `$ inotifywait -r -m .` to watch for file changes to see what is going on:

```
./ CREATE .#index.tsx
./ OPEN,ISDIR 
./ ACCESS,ISDIR 
./ CLOSE_NOWRITE,CLOSE,ISDIR 
./ OPEN,ISDIR 
./ ACCESS,ISDIR 
./ CLOSE_NOWRITE,CLOSE,ISDIR 
```

The `.#index.tsx` is a lock file: https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html
This points to `user@host.pid:boot` which cannot resolved obviously.

With `preact watch` running you can emulate the behavior of emacs by creating a dead symlink:

`ln -s does_not_exist foo`

**Comment by mguentner** [comment]
:point_right:  As a short-term solution, you can set **create-lockfiles** to _nil_ in emacs to prevent `preact watch` from crashing

**Comment by mguentner** [comment]
If you use `yarn`, you can also add this to `package.json`:

```
  "resolutions": {
    "watchpack": "1.6.1"
  },
```

**Comment by developit** [comment]
Does this still happen in the `3.0.0` release?

**Comment by mguentner** [comment]
@developit the problem still happens `preact, 3.0.3`
