### ISSUE TITLE
React-Refresh is in devDependencies array, which breaks the --refresh flag

### ISSUE THREAD

**Issue by RyanChristian4427** [preactjs/preact-cli#1202]
**Do you want to request a _feature_ or report a _bug_?**

This is a bug.

**What is the current behaviour?**

Currently, when running with the refresh flag (`preact watch --refresh`), the following error will be returned: 

```
$ preact watch --port 3000 --refresh
✖ ERROR Error: Cannot find module 'react-refresh/babel'
Require stack:
- /home/x/Projects/y/node_modules/preact-cli/lib/lib/babel-config.js
- /home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/webpack-base-config.js
- /home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js
- /home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/run-webpack.js
- /home/x/Projects/y/node_modules/preact-cli/lib/commands/build.js
- /home/x/Projects/y/node_modules/preact-cli/lib/commands/index.js
- /home/x/Projects/y/node_modules/preact-cli/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at module.exports (/home/x/Projects/y/node_modules/preact-cli/lib/lib/babel-config.js:25:34)
    at module.exports (/home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/webpack-base-config.js:106:3)
    at module.exports (/home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js:345:3)
    at devBuild (/home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:15:21)
    at module.exports (/home/x/Projects/y/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:277:39)
    at module.exports (/home/x/Projects/y/node_modules/preact-cli/lib/commands/watch.js:17:9)
    at Sade.parse (/home/x/Projects/y/node_modules/sade/lib/index.js:190:56)
    at Object.<anonymous> (/home/x/Projects/y/node_modules/preact-cli/lib/index.js:129:6)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

It seems that, like #1200, the `react-refresh` dependency was simply put in the wrong array. Moving it from `devDependencies` to `dependencies` solved the issue in local tests.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Create a new project, add the refresh flag to the `preact watch` command.

**What is the expected behaviour?**

That no errors are caused.

**Please mention other relevant information.**

```
Environment Info:
  System:
    OS: Linux 5.6 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 13.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    preact: ^10.4.0 => 10.4.4 
    preact-cli: ^3.0.0-rc.13 => 3.0.0-rc.13 
    preact-render-to-string: ^5.1.6 => 5.1.8
```

**Comment by RyanChristian4427** [comment]
Closed as fix was merged at #1203
