### ISSUE TITLE
"ERROR TypeError: options.map(...).flat is not a function” when validating arguments

### ISSUE THREAD

**Issue by dogriffiths** [preactjs/preact-cli#1500]
**Do you want to request a _feature_ or report a _bug_?**

I believe this is a bug

**What is the current behaviour?**

I get an error "ERROR TypeError: options.map(...).flat is not a function” when creating a new app.

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Remove any previous global install of react-cli

npm uninstall -g preact-cli

2. Install a new version of react-cli

npm install -g preact-cli

3. Create a new application

preact create default example-app

4. I get this on the command line

````
$ preact create default example-app
  ✖ ERROR TypeError: options.map(...).flat is not a function
      at validateArgs (/Users/davidg/.nvm/versions/node/v10.17.0/lib/node_modules/preact-cli/lib/commands/validate-args.js:4:72)
      at command (/Users/davidg/.nvm/versions/node/v10.17.0/lib/node_modules/preact-cli/lib/commands/create.js:210:2)
      at Sade.parse (/Users/davidg/.nvm/versions/node/v10.17.0/lib/node_modules/preact-cli/node_modules/sade/lib/index.js:189:56)
      at Object.<anonymous> (/Users/davidg/.nvm/versions/node/v10.17.0/lib/node_modules/preact-cli/lib/index.js:83:6)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  $
````

**What is the expected behaviour?**

Expected it to create a new application

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

````
$ preact info

Environment Info:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
    Safari: 14.0.1
  npmGlobalPackages:
    preact-cli: 3.0.5

$````

**Comment by rschristian** [comment]
It's because you're using Node v10 while `.flat()` is v11.

#1493 has brought this up.
