### ISSUE TITLE
Module build failed (from /usr/local/lib/node_modules/preact-cli/node_modules/mini-css-extract-plugin/dist/loader.js):

### ISSUE THREAD

**Issue by philosofonusus** [preactjs/preact-cli#1575]
error:
```
$ preact build
✖ ERROR ./style/index.css
Module build failed (from /usr/local/lib/node_modules/preact-cli/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (./node_modules/postcss-loader/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.loader (./node_modules/postcss-loader/dist/index.js:43:29)
    at /usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/NormalModule.js:316:20
    at /usr/local/lib/node_modules/preact-cli/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/local/lib/node_modules/preact-cli/node_modules/loader-runner/lib/LoaderRunner.js:233:18
 @ ./index.js 1:0-17
```

package.json
```
{
  "private": true,
  "name": "admin",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "build": "preact build",
    "serve": "sirv build --port 8080 --cors --single",
    "dev": "preact watch",
    "lint": "eslint src",
    "test": "jest"
  },
  "eslintConfig": {
    "extends": "preact",
    "ignorePatterns": [
      "build/"
    ]
  },
  "devDependencies": {
    "enzyme": "^3.10.0",
    "enzyme-adapter-preact-pure": "^2.0.0",
    "eslint": "^6.0.1",
    "eslint-config-preact": "^1.1.0",
    "jest": "^24.9.0",
    "jest-preset-preact": "^1.0.0",
    "preact-cli": "^3.0.0",
    "sirv-cli": "1.0.3"
  },
  "dependencies": {
    "preact": "^10.3.2",
    "preact-render-to-string": "^5.1.4",
    "react-router-dom": "^5.2.0"
  },
  "jest": {
    "preset": "jest-preset-preact",
    "setupFiles": [
      "<rootDir>/tests/__mocks__/browserMocks.js",
      "<rootDir>/tests/__mocks__/setupTests.js"
    ]
  }
}
```

**Comment by rschristian** [comment]
Please fill in our issue template rather than deleting & ignoring it. It allows us to help you.

Latest version & freshly initialized project from template works, so we'd need a bit more to go on here.

**Comment by philosofonusus** [comment]
It happens if you do
``` 
npm audit fix
```
I fixed it by just deleting node_modules and package-lock.json

**Comment by rschristian** [comment]
`npm audit fix` is generally not a good idea to ever run. It's just really poor and will often revert package versions by several majors just to get around perceived bugs.

It's important to note that issues for dev tools are very different from issues in production. It often doesn't matter if a dev-only lib has audit issues. It's never exposed.

**Comment by philosofonusus** [comment]
> `npm audit fix` is generally not a good idea to ever run. It's just really poor and will often revert package versions by several majors just to get around perceived bugs.
> 
> It's important to note that issues for dev tools are very different from issues in production. It often doesn't matter if a dev-only lib has audit issues. It's never exposed.

Ok thank you
