### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined when tryting to use React-PDF with preact-cli

### ISSUE THREAD

**Issue by ljmerza** [preactjs/preact-cli#1702]
**What is the current behaviour?**
```
Uncaught ReferenceError: Buffer is not defined
    at eval (util.js?9eb9:103:1)
    at ../node_modules/core-util-is/lib/util.js (bundle.js:2882:1)
    at __webpack_require__ (bundle.js:833:30)
    at fn (bundle.js:130:20)
    at Object.eval (_stream_readable.js?3281:67:1)
    at eval (_stream_readable.js:1040:30)
    at ../node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_readable.js (bundle.js:5015:1)
    at __webpack_require__ (bundle.js:833:30)
    at fn (bundle.js:130:20)
    at eval (readable-browser.js?346c:1:1)
```

**Steps to Reproduce**

install react-pdf and try to use it

Here is my config

```
const webpack = require('webpack')

export default (config, env, helpers, options) => {

  config.node.Buffer = true

  config.plugins = [
    ...config.plugins,
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer']
    })
  ]
}
```

**Comment by rschristian** [comment]
> install react-pdf and try to use it

Please provide reproduction steps, i.e., Add `foo` to `src/index.js`, run `npm run build`, etc.

**Comment by rschristian** [comment]
Closing this out as no reproduction has been provided. A minimal Git repo or CodeSandbox is necessary. Unfortunately, OSS maintainers can't afford the time to try to reproduce your error by trial and error.

If you are able to provide a reproduction, I'd be happy to re-open and look into it if it's a Preact-CLI issue (though sounds more like a Webpack / lib issue).
