### ISSUE TITLE
3.0.0-next.16 template.html problems

### ISSUE THREAD

**Issue by 7Ds7** [preactjs/preact-cli#728]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behaviour?**

/template.html is not aware of changes, --template flag fails to build

**If the current behaviour is a bug, please provide the steps to reproduce.**

create a project with ```preact create default <name>```

- watch with--template  flag  ``preact watch --template src/template.html``` leads to (run as npm run dev and changed package.json.scripts.dev) 
```
Build failed!

✖ ERROR Template execution failed: TypeError: htmlWebpackPlugin.options.createLoadManifest is not a function
✖ ERROR   TypeError: htmlWebpackPlugin.options.createLoadManifest is not a function
```

- watch without --template flag 

any changes made to the /template.html file are not used

**What is the expected behaviour?**
```--watch``` flag should not fail to build
or
preact-cli should use the /template.html

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version v9.11.1
- npm version 6.7.0
- Operating system MacOs Mojave 10.14.3
- CLI version 3.0.0-next.16
- Browser (irrelevant)

**Comment by prateekbh** [comment]
so with v3. the `template.html` in `src` should just work out of the box

- `preact watch`
- change title in `src/template.html`
- reload
- should work


Please confirm

**Comment by douggr** [comment]
> so with v3. the `template.html` in `src` should just work out of the box
> 
>     * `preact watch`
>     * change title in `src/template.html`
>     * reload
>     * should work
> 
> 
> Please confirm

Yes! Confirmed with 3.0.0-rc5.

Not sure why yet, but something weird happens if you set the `--template` flag; my `template.html` used to be in the root directory, but it doesn't actually matter, I moved it to `src/index.html` and tried again, no success. Most awkward this is kinda random:

```shell
$ API_BASE_URL="http://localhost:8042" yarn start
yarn run v1.17.3
$ preact watch --template template.html
✖ ERROR Error: ENOENT: no such file or directory, open '$PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/template.html'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at read ($PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/render-html-plugin.js:14:9)
    at module.exports ($PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/render-html-plugin.js:27:16)
    at clientConfig ($PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js:89:14)
    at module.exports ($PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js:347:9)
    at devBuild ($PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:15:21)
    at module.exports ($PATH/test--typescript/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:255:39)
    at module.exports ($PATH/test--typescript/node_modules/preact-cli/lib/commands/watch.js:17:9)
    at Sade.parse ($PATH/test--typescript/node_modules/sade/lib/index.js:169:56)
    at Object.<anonymous> ($PATH/test--typescript/node_modules/preact-cli/lib/index.js:120:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Done in 2.08s.
```

**Comment by prateekbh** [comment]
I would suggest renaming and moving your template to `template.html`. There is an ative discussion if preact-cli should move away from `--template` as there is an easier more intuitive way of doing it in v3
