### ISSUE TITLE
it have throw a error when i replacing .css files with .scss files:

### ISSUE THREAD

**Issue by webKity** [preactjs/preact-cli#887]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
it have throw a error when i replacing .css files with .scss files:
```
 ERROR ./components/common.scss (../node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--6-0!./components/common.scss)
Module build failed (from ../node_modules/preact-cli/lib/lib/webpack/proxy-loader.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (./node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (./node_modules/sass-loader/dist/index.js:36:28)
    at Object.proxyLoader (./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js:26:16)
 @ ./components/common.scss 2:14-241 21:1-42:3 22:19-246
 @ ./root.tsx
 @ ./index.js
 @ ../node_modules/preact-cli/lib/lib/entry.js
 @ multi ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```
**If the current behaviour is a bug, please provide the steps to reproduce.**
replacing .css files with .scss files

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

**Comment by webKity** [comment]
This problem is caused by sass-loader; i use the sass-loader@7.1.0 is ok
