### ISSUE TITLE
Sass loader error on fresh new project

### ISSUE THREAD

**Issue by peterbe** [preactjs/preact-cli#894]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
I get this error when typing `yarn start`

```
Build failed!

✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--2-0!./src/style/index.scss
Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/peterbe/dev/JAVASCRIPT/groce-web/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/peterbe/dev/JAVASCRIPT/groce-web/node_modules/sass-loader/dist/index.js:36:28)
    at Object.proxyLoader (/Users/peterbe/dev/JAVASCRIPT/groce-web/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js:23:16)
 @ ./src/style/index.scss 4:14-216 18:2-22:4 19:20-222
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--2-0!./src/components/header/style.scss
Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/peterbe/dev/JAVASCRIPT/groce-web/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/peterbe/dev/JAVASCRIPT/groce-web/node_modules/sass-loader/dist/index.js:36:28)
    at Object.proxyLoader (/Users/peterbe/dev/JAVASCRIPT/groce-web/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js:23:16)
 @ ./src/components/header/style.scss 4:14-225 18:2-22:4 19:20-231
 @ ./src/components/header/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--2-0!./src/routes/home/style.scss
Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users./src/routes/home/index.js
 @ ./src/routes/home/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--2-0!./src/routes/profile/style.scss
Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users./src/routes/profile/index.js
 @ ./src/routes/profile/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. `npx preact create --git --yarn --install --sass default groce-web`
2. `cd groce-web`
3. `yarn start`

**What is the expected behaviour?**
That it'd work.

**Please mention other relevant information.**

Please paste the results of `preact info` here.
```
▶ preact info
         ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

Commands:
  create [template] [dest]  Create a new application.
  build [src] [dest]        Create a production build in build/
  watch [src]               Start a development live-reload server.
  serve [dir]               Start an HTTP2 static fileserver.
  list                      List all official templates

Options:
  -h, --help  Show help                                                [boolean]

Unknown argument: info
```

The version(s) I got, at the time of writing was this:

```json
{
  "name": "groce-web",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "if-env NODE_ENV=production && yarn run -s serve || yarn run -s dev",
    "build": "preact build",
    "serve": "preact build && preact serve",
    "dev": "preact watch",
    "test": "eslint src && preact test"
  },
  "eslintConfig": {
    "extends": "eslint-config-synacor"
  },
  "devDependencies": {
    "eslint": "6.4.0",
    "eslint-config-synacor": "3.0.5",
    "if-env": "1.0.4",
    "node-sass": "4.12.0",
    "preact-cli": "2.2.1",
    "sass-loader": "8.0.0"
  },
  "dependencies": {
    "preact": "8.5.2",
    "preact-compat": "3.19.0",
    "preact-router": "2.6.1"
  }
}
```

**Comment by peterbe** [comment]
Closing in favor of https://github.com/preactjs/preact-cli/issues/880
